name: Run Batch Prediction via modelapp.py

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  batch_predict:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure boto3, tensorflow, etc. are included.

    # Step 4: Set AWS credentials for accessing S3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"  # Replace this with your actual region

    # Step 5: Download model from S3 to the workspace
    - name: Download model from S3
      run: |
        aws s3 cp s3://mybucketgithub/Image_resnet50.h5 ./Image_resnet50.h5  # Adjust S3 path if necessary

    # Step 6: Run the FastAPI app
    - name: Run FastAPI app
      run: |
        python modelapp.py
