name: Run Batch Prediction via modelapp.py

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  batch_predict:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirments.txt  # Fix typo: 'requirments.txt' should be 'requirements.txt'

    # Step 4: Set Google Cloud credentials
    - name: Set Google Cloud credentials
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > /tmp/gcp_key.json
        export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcp_key.json"
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    # Step 5: Run modelapp.py directly with batch argument
    - name: Run batch predictions using modelapp.py
      run: |
        python modelapp.py batch  # Trigger batch processing in your script

    # Optional: Show logs after the batch run
    - name: Show log output
      run: |
        cat mylog.txt  # Ensure this log file exists and the correct path is specified
