name: Run Batch Prediction via modelapp.py

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  batch_predict:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirments.txt

    - name: Set Google Cloud credentials
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > /tmp/gcp_key.json
        export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcp_key.json"

    - name: Run batch predictions using modelapp.py
      run: |
        python modelapp.py batch

    - name: Show log output
      run: |
        cat mylog.txt
