name: Run Batch Prediction via FastAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  batch_predict:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn Pillow google-cloud-storage tensorflow

    # Step 4: Set Google Cloud credentials using a secret
    - name: Set Google Cloud credentials
      run: |
        echo "$GOOGLE_APPLICATION_CREDENTIALS" > /tmp/gcp_key.json
        export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcp_key.json"
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    # Step 5: Start FastAPI server in the foreground
    - name: Start FastAPI server
      run: |
        nohup uvicorn modelapp:app --host 0.0.0.0 --port 8000 > fastapi.log 2>&1 &
    
    # Step 6: Check server readiness and wait until it is ready
    - name: Wait for FastAPI to be ready
      run: |
        for i in {1..15}; do
          curl --silent --fail http://localhost:8000/ || sleep 5;
        done

    # Step 7: Trigger batch prediction from GCS
    - name: Perform batch prediction
      run: |
        curl http://localhost:8000/predict-from-gcs-folder

    # Step 8: Check FastAPI logs for debugging
    - name: Show FastAPI logs
      run: cat fastapi.log
